services:
  web_service:
    build:
      context: .
      dockerfile: web_service/Dockerfile
    ports:
      - 5001:5001
    environment:
      - FLASK_ENV=testing
    volumes:
      - scans_test:/mnt/scans
      - data_test:/app/data
      - preview_images_test:/app/src/static/images/pdfpreview
    networks:
      - test-network
    # depends_on:
    #   - rabbitmq

  # rabbitmq:
  #   image: rabbitmq:4.0.7-management
  #   ports:
  #   - "5673:5672"
  #   - "15673:15672"
  #   networks:
  #     - test-network

  test_service:
    build:
      context: .
      dockerfile: test_service/Dockerfile
    depends_on:
      - web_service
      - redis
    networks:
      - test-network
    volumes:
      - scans_test:/mnt/scans
      - data_test:/app/data
      - preview_images_test:/app/preview-images
      - ./detection_service:/tests/tests/detection_service
      - ./web_service:/tests/tests/web_service
  
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis_test
    ports:
      - "6380:6379"
    networks:
      - test-network
    environment:
      - REDIS_URL=redis://redis:6379

volumes:
  scans_test:
  data_test:
  preview_images_test:

networks:
  test-network: