services:    
  smb_service:
    build: ./smb_service
    container_name: smb_service
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    volumes:
      - scans:/shares/Scans
    restart: unless-stopped
    networks:
      - app-network

  ocr_service:
    build:
      context: .
      dockerfile: ocr_service/Dockerfile
    restart: unless-stopped
    volumes:
      - scans:/mnt/scans
      - data:/app/data
    networks:
      - app-network
    depends_on:
      - smb_service
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 2
    command: ["python", "main.py"]

  openai_service:
    build:
      context: .
      dockerfile: openai_service/Dockerfile
    restart: unless-stopped
    volumes:
      - scans:/mnt/scans
      - data:/app/data
    networks:
      - app-network
    depends_on:
      - smb_service
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 1
    command: ["python", "main.py"]

  detection_service:
    build:
      context: .
      dockerfile: detection_service/Dockerfile
    container_name: detection_service
    restart: unless-stopped
    volumes:
      - scans:/mnt/scans
      - data:/app/data
    networks:
      - app-network
    depends_on:
      - smb_service
      - rabbitmq
    command: ["python", "main.py"]
  
  metadata_service:
    build:
      context: .
      dockerfile: metadata_service/Dockerfile
    restart: unless-stopped
    volumes:
      - scans:/mnt/scans
      - preview-images:/app/preview-images
      - data:/app/data
    networks:
      - app-network
    depends_on:
      - smb_service
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 2
    command: ["python", "main.py"]
  
  upload_service:
    build:
      context: .
      dockerfile: upload_service/Dockerfile
    container_name: upload_service
    restart: unless-stopped
    volumes:
      - scans:/mnt/scans
      - data:/app/data
    networks:
      - app-network
    depends_on:
      - smb_service
      - rabbitmq
    command: ["python", "main.py"]
  
  web_service:
    image: web_service
    restart: unless-stopped
    build:
      context: .
      dockerfile: web_service/Dockerfile
    ports:
      - 5001:5001
    environment:
      - FLASK_ENV=development # prod or development
    volumes:
      - ./web_service/src:/app/src  # Only for development!!
      - scans:/mnt/scans
      - data:/app/data
      - preview-images:/app/src/static/images/pdfpreview
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:4.0.7-management"
    restart: unless-stopped
    container_name: "rabbitmq"
    environment:
      - TZ=Europe/Berlin
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  scans:
  preview-images:
  data:

networks:
  app-network: