services:    
  smb_service:
    build: ./smb_service
    container_name: smb_service
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    volumes:
      - scans:/shares/Scans
    restart: unless-stopped
    networks:
      - app-network

  ocr_service:
    build: ./ocr_service
    restart: unless-stopped
    volumes:
      - ./ocr_service:/ocr_service
      - scans:/mnt/scans
      - ./shared:/ocr_service/shared
    working_dir: /ocr_service
    networks:
      - app-network
    depends_on:
      - smb_service
      - rabbitmq
    command: ["python", "main.py"]

  detection_service:
    build: ./detection_service
    container_name: detection_service
    restart: unless-stopped
    volumes:
      - ./detection_service:/detection_service
      - scans:/mnt/scans
      - ./shared:/detection_service/shared
    working_dir: /detection_service
    networks:
      - app-network
    depends_on:
      - smb_service
      - rabbitmq
    command: ["python", "main.py"]
  
  metadata_service:
    build: ./metadata_service
    restart: unless-stopped
    volumes:
      - ./metadata_service:/metadata_service
      - scans:/mnt/scans
      - ./shared:/metadata_service/shared
      - preview-images:/shared/preview-images
    working_dir: /metadata_service
    networks:
      - app-network
    depends_on:
      - smb_service
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 2
    command: ["python", "main.py"]
  
  upload_service:
    build: ./upload_service
    container_name: upload_service
    restart: unless-stopped
    volumes:
      - ./upload_service:/upload_service
      - scans:/mnt/scans
      - ./shared:/upload_service/shared
      - data:/app/data
    working_dir: /upload_service
    networks:
      - app-network
    depends_on:
      - smb_service
      - rabbitmq
    command: ["python", "main.py"]
  
  web_service:
    image: web_service
    restart: unless-stopped
    build: ./web_service
    ports:
      - 5001:5001
    environment:
      - FLASK_ENV=production
    volumes:
      - ./web_service:/app  # TODO: Only for development!!
      - scans:/mnt/scans
      - data:/app/data
      - ./shared:/app/shared
      - preview-images:/app/src/static/images/pdfpreview
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:4.0.7-management"
    restart: unless-stopped
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  scans:
  shared:
  preview-images:
  data:

networks:
  app-network: