services:    
  smb-service:
    build: ./smb-service
    container_name: smb-service
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    volumes:
      - scans:/shares/Scans
    restart: unless-stopped
    networks:
      - app-network

  ocr-service:
    build: ./ocr-service
    container_name: ocr-service
    restart: unless-stopped
    volumes:
      - ./ocr-service:/ocr-service
      - scans:/mnt/scans
      - ./shared:/ocr-service/shared
    working_dir: /ocr-service
    networks:
      - app-network
    depends_on:
      - smb-service
      - rabbitmq
    command: ["python", "main.py"]

  detection-service:
    build: ./detection-service
    container_name: detection-service
    restart: unless-stopped
    volumes:
      - ./detection-service:/detection-service
      - scans:/mnt/scans
      - ./shared:/detection-service/shared
      - preview-images:/shared/preview-images
    working_dir: /detection-service
    networks:
      - app-network
    depends_on:
      - smb-service
      - rabbitmq
    command: ["python", "main.py"]
  
  upload-service:
    build: ./upload-service
    container_name: upload-service
    restart: unless-stopped
    volumes:
      - ./upload-service:/upload-service
      - scans:/mnt/scans
      - ./shared:/upload-service/shared
      - data:/app/data
    working_dir: /upload-service
    networks:
      - app-network
    depends_on:
      - smb-service
      - rabbitmq
    command: ["python", "main.py"]
  
  web-service:
    image: web-service
    restart: unless-stopped
    build: ./web-service
    ports:
      - 5001:5001
    environment:
      - FLASK_ENV=development
    volumes:
      - ./web-service:/app  # TODO: Only for development!!
      - scans:/mnt/scans
      - data:/app/data
      - ./shared:/app/shared
      - preview-images:/app/src/static/images/pdfpreview
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:4.0.7-management"
    restart: unless-stopped
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  scans:
  shared:
  preview-images:
  data:

networks:
  app-network: