name: ESLint Check

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.css'
      - '**/*.md'
  push:
    paths:
      - '**/*.js'
      - '**/*.css'
      - '**/*.md'
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint . --max-warnings 999 || echo "ESLint found errors"

      - name: Fail on errors
        run: |
          ERRORS=$(npx eslint . -f json | jq '.[].messages[] | select(.severity == 2)' | wc -l)
          echo "Number of errors: $ERRORS"
          if [ "$ERRORS" -gt 0 ]; then
            echo "❌ ESLint errors found!"
            exit 1
          else
            echo "✅ No blocking ESLint errors."
          fi