name: Flake8 Lint

on:
    push:
        paths:
            - '**.py'
    pull_request:
        paths:
            - '**.py'

jobs:
    flake8:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'
            - name: Install flake8
              run: pip install flake8
            - name: Run flake8
              run: |
                # stop the build if there are Python syntax errors or undefined names
                echo "Running Flake8 for critical errors"
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                echo "Running general Flake8"
                flake8 . --config=.flake8 --exit-zero