name: Merge Requirements

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'requirements-dev.txt'
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  merge-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Find and merge all requirements.txt files
        run: |
          echo "Searching for requirements.txt files..."
          find . -name "requirements.txt" > requirements_files.txt

          echo "Merging requirements..."
          > merged_requirements.in

          while read -r file; do
            echo "# From $file" >> merged_requirements.in
            cat "$file" >> merged_requirements.in
            echo "" >> merged_requirements.in
          done < requirements_files.txt

          echo "Compiling merged requirements..."
          set +e
          pip-compile merged_requirements.in --output-file=requirements-dev.txt
          RESULT=$?
          set -e

          if [ $RESULT -ne 0 ]; then
            echo "❌ Conflict detected during pip-compile:"
            pip-compile merged_requirements.in --output-file=requirements-dev.txt || true
            exit 1
          fi

          echo "✅ requirements-dev.txt successfully created:"
          cat requirements-dev.txt

      - name: Commit and push requirements-dev.txt
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add requirements-dev.txt
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git add requirements-dev.txt
            git commit -m "Update requirements-dev.txt [ci-skip-auto]"
            git push origin main
          fi