name: Generate requirements-dev.txt

on:
  push:
    branches:
      - main

jobs:
  generate-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false # sonst wird GITHUB_TOKEN statt deines PAT genutzt
          fetch-depth: 0             # sonst schlägt git push fehl

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs

      - name: Generate requirements-dev.txt
        run: |
          pipreqs . --force --ignore .venv --savepath requirements-dev.txt

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          message: "Update requirements-dev.txt [skip ci]"