name: Generate requirements-dev.txt

on:
  push:
    branches:
      - main

jobs:
  generate-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs

      - name: Generate requirements-dev.txt
        run: |
          pipreqs . --force --ignore .venv --savepath requirements-dev.txt

      - name: Push requirements-dev.txt
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add requirements-dev.txt
          git commit -m "Update requirements-dev.txt" || echo "No changes"
          git push https://x-access-token:$GH_PAT@github.com/${{ github.repository }}.git HEAD:main